Repository JoinSEEDS/seeds_light_wallet, pull requests merged in 2021-02, with the labels that each got.

#497 Profile bloc
  lib/screens/app/profile/profile_bloc.dart
  lib/screens/app/profile/profile_repository.dart
  lib/screens/app/profile/profile_screen.dart
  pubspec.yaml
Labels: enhancement, v2

#513 Wallet explore
  lib/v2/datasource/remote/api/balance_repository.dart
  lib/v2/datasource/remote/api/profile_repository.dart
  lib/v2/datasource/remote/api/voice_repository.dart
  lib/v2/datasource/remote/model/balance_model.dart
  lib/v2/datasource/remote/model/voice_model_alliance.dart
  lib/v2/datasource/remote/model/voice_model_campaign.dart
  lib/v2/domain-shared/result_to_state_mapper.dart
  lib/v2/domain-shared/results_to_state_mapper.dart
  lib/v2/screens/explore/components/explore_info_card.dart
  lib/v2/screens/explore/explore_screen.dart
  lib/v2/screens/explore/interactor/explore_bloc.dart
  lib/v2/screens/explore/interactor/mappers/explore_state_mapper.dart
  lib/v2/screens/explore/interactor/usecases/get_explore_page_data_use_case.dart
  lib/v2/screens/explore/interactor/viewmodels/explore_events.dart
  lib/v2/screens/explore/interactor/viewmodels/explore_state.dart
  lib/v2/screens/profile/components/profile_header.dart
  lib/v2/screens/profile/interactor/mappers/profile_state_mapper.dart
  lib/v2/screens/profile/interactor/profile_bloc.dart
Labels: v2

#514 Wallet explore: Planted Seeds
  lib/constants/http_mock_response.dart
  lib/models/models.dart
  lib/providers/notifiers/planted_notifier.dart
  lib/providers/services/http_service.dart
  lib/screens/app/ecosystem/overview.dart
  lib/v2/datasource/remote/api/balance_repository.dart
  lib/v2/datasource/remote/api/planted_repository.dart
  lib/v2/datasource/remote/model/planted_model.dart
  lib/v2/screens/explore/explore_screen.dart
  lib/v2/screens/explore/interactor/mappers/explore_state_mapper.dart
  lib/v2/screens/explore/interactor/usecases/get_explore_page_data_use_case.dart
  lib/v2/screens/explore/interactor/viewmodels/explore_state.dart
Labels: v2

#521 Fix citizenship card
  assets/images/lotus.svg
  lib/v2/screens/profile/components/profile_bottom.dart
  lib/v2/screens/profile/components/profile_header.dart
  lib/v2/screens/profile/components/profile_middle.dart
Labels: enhancement, v2

#528 App color used on focus input.
  lib/i18n/set_currency.i18n.dart
  lib/providers/services/navigation_service.dart
  lib/v2/components/text_form_field_custom.dart
  lib/v2/datasource/remote/api/rates_repository.dart
  lib/v2/screens/profile/components/profile_middle.dart
  lib/v2/screens/settings/edit_name/edit_name_screen.dart
  lib/v2/screens/settings/set_currency/interactor/viewmodels/set_currency_state.dart
  lib/v2/screens/settings/set_currency/set_currency_screen.dart
Labels: bug, v2

#526 Bloc observer added
  lib/main.dart
  lib/v2/datasource/remote/api/eos_repository.dart
  lib/v2/domain-shared/bloc_observer.dart
  lib/v2/screens/settings/edit_name/edit_name_screen.dart
Labels: enhancement, v2

#541 Added generic full page loading indicator and generic full page error
  lib/v2/components/full_page_error_indicator.dart
  lib/v2/components/full_page_loading_indicator.dart
  lib/v2/screens/explore/explore_screen.dart
Labels: v2

#543 Profile avatar widget added
  lib/v2/components/profile_avatar.dart
  lib/v2/screens/profile/components/profile_header.dart
  lib/v2/screens/profile/interactor/viewmodels/bloc.dart
  lib/v2/screens/profile/interactor/viewmodels/profile_bloc.dart
  lib/v2/screens/profile/interactor/viewmodels/profile_event.dart
  lib/v2/screens/profile/profile_screen.dart
Labels: enhancement, v2

#545 Support screen
  assets/images/lotus_support_big.svg
  assets/images/lotus_support_small.svg
  lib/i18n/support.i18n.dart
  lib/providers/services/navigation_service.dart
  lib/v2/screens/profile/components/profile_bottom.dart
  lib/v2/screens/profile/support/support_screen.dart
  pubspec.yaml
Labels: v2

#549 Cache singleton
  lib/main.dart
  lib/v2/datasource/settings_storage.dart
Labels: enhancement, v2

#547 Edit name 2
  lib/i18n/edit_name.i18n.dart
  lib/v2/components/text_form_field_custom.dart
  lib/v2/datasource/remote/api/eos_repository.dart
  lib/v2/datasource/remote/api/profile_repository.dart
  lib/v2/datasource/remote/model/transaction_response.dart
  lib/v2/screens/settings/edit_name/edit_name_screen.dart
  lib/v2/screens/settings/edit_name/interactor/mappers/update_profile_state_mapper.dart
  lib/v2/screens/settings/edit_name/interactor/usecases/update_profile_use_case.dart
  lib/v2/screens/settings/edit_name/viewmodels/edit_name_bloc.dart
  lib/v2/screens/settings/edit_name/viewmodels/edit_name_event.dart
Labels: enhancement, v2
